"""Update university

Revision ID: dac111a7134f
Revises: 4d5b6d12428a
Create Date: 2023-07-29 00:05:04.171681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac111a7134f'
down_revision = '4d5b6d12428a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('description', sa.String(), nullable=True))
    op.add_column('university', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'phone')
    op.drop_column('university', 'description')
    # ### end Alembic commands ###
